<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Arunas-MacBook-Pro.local" failures="2" tests="2" name="Test" time="0.041" errors="0" timestamp="2021-07-09T18:23:36 MST">
  <testcase classname="testNGDemos.ExpectedException" name="exceptionTestOne" time="0.007">
    <failure type="org.testng.TestException" message="
Expected exception of any of types [class java.io.IOException, class java.lang.NullPointerException] but got java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Expected exception of any of types [class java.io.IOException, class java.lang.NullPointerException] but got java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.Exception
at testNGDemos.ExpectedException.exceptionTestOne(ExpectedException.java:17)
... 22 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- exceptionTestOne -->
  <testcase classname="testNGDemos.ExpectedException" name="testException" time="0.001">
    <failure type="org.testng.TestException" message="
Method ExpectedException.testException()[pri:0, instance:testNGDemos.ExpectedException@7e9131d5] should have thrown an exception of type class java.lang.ArithmeticException">
      <![CDATA[org.testng.TestException: 
Method ExpectedException.testException()[pri:0, instance:testNGDemos.ExpectedException@7e9131d5] should have thrown an exception of type class java.lang.ArithmeticException
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testException -->
</testsuite> <!-- Test -->
